# Generated by Django 4.2.8 on 2023-12-11 13:37

from django.db import migrations, models
import users.enums


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useryamdb',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='useryamdb',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('user', 'USER'), ('moderator', 'MODERATOR')], default=users.enums.UserRole['USER'], max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='useryamdb',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='useryamdb',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='useryamdb',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='useryamdb',
            name='username',
            field=models.CharField(max_length=200, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
