# Generated by Django 4.2.8 on 2023-12-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useryamdb_options_alter_useryamdb_date_joined_and_more'),
        ('users', '0002_alter_useryamdb_options_useryamdb_role_and_more'),
    ]

    operations = [
    ]
