# Generated by Django 4.2.8 on 2023-12-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20231211_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useryamdb',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='useryamdb',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
